collections:
  - name: community.crypto
    version: ==3.1.0
  - name: community.docker
    version: ==5.0.5
  - name: community.general
    version: ==12.3.0
  - name: community.postgresql
    version: ==4.2.0
  - name: community.sops
    version: ==2.2.7
  - name: containers.podman
    version: ==1.18.1
  - name: https://github.com/maxhoesel-ansible/ansible-collection-smallstep
    type: git
    version: 8f088f21b59ff685327ae68ff749b17f3a8d597d
  - name: prometheus.prometheus
    version: ==0.27.5
