---
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: apt
  when: ansible_facts['os_family'] == "Debian"
  
- name: Add OpenTofu Repository
  become: true
  ansible.builtin.deb822_repository:
    name: opentofu
    types:
      - deb
      - deb-src
    uris: https://packages.opentofu.org/opentofu/tofu/any/
    suites: [any]
    components: [main]
    signed_by: https://packages.opentofu.org/opentofu/tofu/gpgkey
    state: present
    enabled: true

- name: Install OpenTofu
  become: true
  ansible.builtin.apt:
    name:
      - tofu
    state: present
    update_cache: true
  when: '"tofu" not in ansible_facts.packages'
