labnet:
  hosts:
    container.labnet:
    fireeye.labnet:
    workstation.labnet:

ca:
  hosts:
    container.labnet:

hypervisor:
  hosts:
    workstation.labnet:

domains:
  hosts:
    media.workstation.labnet:

artifactstores:
  hosts:
    container.labnet:
    fireeye.labnet:

authservers:
  hosts:
    # container.labnet:

gpu_intel:
  hosts:
    container.labnet:
    oszm1.labnet:

desktops:
  hosts:
    fireeye.labnet:
    workstation.labnet:

hires_desktops:
  hosts:
    workstation.labnet:

servicehosts:
  hosts:
    container.labnet:
    fireeye.labnet:
    workstation.labnet:

dbhosts:
  hosts:
    container.labnet:
    fireeye.labnet:
    workstation.labnet:

dnsresolvers:
  hosts:
    container.labnet:

mediaservers:
  hosts:
    fireeye.labnet:

metricsmonitors:
  hosts:
    fireeye.labnet:
    workstation.labnet:

kittens:
  hosts:
    workstation.labnet:

oszm1:
  hosts:
    oszm1.labnet:
