---
- name: Update dconf
  become: true
  ansible.builtin.command: dconf update
  changed_when: true

- name: Enable cage Service
  become: true
  ansible.builtin.systemd:
    name: cage.service
    enabled: true

- name: Enable FYC Service
  become: true
  ansible.builtin.systemd:
    name: fuck-your-cursor.service
    enabled: true
