ca_root_password: ENC[AES256_GCM,data:gDg/3OexEF5IcbbqSOfQc/sIRMitQnJZMC6i/XSDtsI=,iv:xdR6IexLEMBZZVjOhisUhqvR4/IFw475fm91ters0OA=,tag:PIYHdCU89lQ1sy8OCvnYEA==,type:str]
media_credentials_file: ENC[AES256_GCM,data:7DiISv2NYS1W4O8CCcobOgbH+SJvXteU,iv:KEF87dlA9xaWp1mSIqorsGtKcuXtj3bcvd4UWFYT8tU=,tag:FWoh9BmrGtGy3CNVCkTRWQ==,type:str]
media_ip_address: ENC[AES256_GCM,data:B0aXW6bSNnqaIN8yWA==,iv:OiQXUoiOzdVqCrxC8dRrVsmslMBjtiGNJiZPndpfvIU=,tag:C1wplBVnd9IMuHDQ0t2ADg==,type:str]
media_location: ENC[AES256_GCM,data:dZ6qzXbtWUYGX/tIuNLYGnHqCeBIhys=,iv:r5odFEcEN4TRDJ1pXPRkvikWAL5o5TNXTgqIwp/lLyc=,tag:n26slFMNI2H8GUV1LiKrOQ==,type:str]
media_mount: ENC[AES256_GCM,data:EVMkzHhJCMQTJpfpNqI=,iv:Jfs0TU1oPoUj63K50+jR0Hnz7FrY8fVC1WdgonNmAKw=,tag:l6IJp9nm2T/sPz1eV/qN4g==,type:str]
media_wol_address: ENC[AES256_GCM,data:G+uHVl1gHPlLWIKQdkIOqoI=,iv:PdL5zNW/FzlHbcHMSglL37lrP7LwYZCmQ14yscNPDGM=,tag:AGQFkHXTQg9WZ27+DLfQqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pan98cxr43vkcty4lr2krz0lv9tcfh48dl29vft28jv54txyts7qcxwshn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ODA5aWdkTzZvSVBzeHpH
            YUt4blB0U2lqQ1V1TE1NMVFXZGVIdGk1UFZjCitUeHViNW5wekZmQ2x5MDNwQjVi
            YW91clVZZjYrYTVtOVRIK2RvZHdiSjAKLS0tIEluT2hWaG9KWFBMZWdyOU53RnAy
            ei9iam02cWZOTjBEK0JiM2VJNlh4OVkKOcd8+wLEG/May3gaiwT+4oqg49vCuYbN
            MOQLSBXhiMD5KLPlpDBDgCB0td6Ulh7QlcjSwXWUGhDDDykAMh0OZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T12:16:41Z"
    mac: ENC[AES256_GCM,data:Zx9URc3SeA0BX5O7C/n96+DBizSz/WrK3KWIconQFmQntfJzIs/CQPjPOrCoWah9PpwUeNRgIzzq9fYlXBa9Qz3c6rE1bR0e/J8LuP2t83xMPR21v07C9a2UVphD4fhiccCrzyUZQ5jM4z1q9P5cY104Mji4Ft/FcaV6trj2MoI=,iv:j7ueLOhGyrVwYlcG9R2mOGUyApmgfx6WDu1C31sfbL8=,tag:/w1gTsJSwuIbyK3CwQk52g==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
