---
podman_jellyseerr_id: jellyseerr
podman_jellyseerr_name: Jellyseerr
podman_jellyseerr_groups:
  - service

podman_jellyseerr_basedir: /mnt/usb/jellyseerr
podman_jellyseerr_mediadir: "{{ media_mount }}"
podman_jellyseerr_version: latest

podman_jellyseerr_pg_user: jellyseerr
podman_jellyseerr_pg_password: podman_jellyseerr_password
podman_jellyseerr_pg_db: jellyseerr
