---
- name: Create groups
  become: true
  register: _podman_seerr_groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
    system: true
  loop: "{{ podman_seerr_groups }}"
  notify: Restart seerr

- name: Ensure user is a group member
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ podman_seerr_groups }}"
    append: true
  notify: Restart seerr

- name: Create user
  become: true
  register: _podman_seerr_user
  ansible.builtin.user:
    comment: "{{ podman_seerr_name }}"
    create_home: false
    group: "{{ _podman_seerr_groups.results[0].gid }}"
    groups: "{{ podman_seerr_groups }}"
    home: "{{ podman_seerr_basedir }}"
    name: "{{ podman_seerr_id }}"
    password: "!"
    shell: "/usr/sbin/nologin"
    system: true
  notify: Restart seerr


- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ podman_seerr_basedir }}"
    state: directory
    owner: "{{ _podman_seerr_user.uid }}"
    group: "{{ _podman_seerr_groups.results[0].gid }}"
    mode: "u=rwX,g=rX,o="
    recurse: true
  notify: Restart seerr

- name: Ensure directories exist
  become: true
  ansible.builtin.file:
    path: "{{ podman_seerr_basedir }}/{{ item }}"
    state: directory
    owner: "{{ _podman_seerr_user.uid }}"
    group: "{{ _podman_seerr_groups.results[0].gid }}"
    mode: "u=rwX,g=rX,o="
    recurse: true
  loop:
    - config
  notify: Restart seerr


- name: Create postgres user
  register: podman_seerr_result
  retries: 3
  delay: 3
  until: podman_seerr_result is not failed
  community.postgresql.postgresql_user:
    login_host: localhost
    login_password: "{{ podman_postgres_master_password }}"
    login_user: "{{ podman_postgres_master_user }}"
    name: "{{ podman_seerr_pg_user }}"
    password: "{{ podman_seerr_pg_password }}"
  notify: Restart seerr

- name: Create postgres database
  register: podman_seerr_result
  retries: 3
  delay: 3
  until: podman_seerr_result is not failed
  community.postgresql.postgresql_db:
    login_host: localhost
    login_password: "{{ podman_postgres_master_password }}"
    login_user: "{{ podman_postgres_master_user }}"
    name: "{{ podman_seerr_pg_db }}-{{ item }}"
    owner: "{{ podman_seerr_pg_user }}"
  loop:
    - main
    - log
  notify: Restart seerr

- name: "GRANT ALL PRIVILEGES ON DATABASE 'db' TO 'user'"
  community.postgresql.postgresql_privs:
    login_host: localhost
    login_password: "{{ podman_postgres_master_password }}"
    login_user: "{{ podman_postgres_master_user }}"
    login_db: postgres
    privs: ALL
    type: database
    obj: "{{ podman_seerr_pg_db }}-{{ item }}"
    role: "{{ podman_seerr_pg_user }}"
  loop:
    - main
    - log
  notify: Restart seerr

- name: "GRANT USAGE, CREATE ON SCHEMA PUBLIC TO 'user'"
  community.postgresql.postgresql_privs:
    login_host: localhost
    login_password: "{{ podman_postgres_master_password }}"
    login_user: "{{ podman_postgres_master_user }}"
    login_db: postgres
    privs: CREATE
    type: schema
    obj: public
    role: "{{ podman_seerr_pg_user }}"
  notify: Restart seerr


#- name: Copy configuration
#  become: true
#  ansible.builtin.template:
#    src: "config.xml.j2"
#    dest: "{{ podman_seerr_basedir }}/config/config.xml"
#    owner: "{{ _podman_seerr_user.uid }}"
#    group: "{{ _podman_seerr_groups.results[0].gid }}"
#    mode: "0o640"
#  notify: Restart seerr


- name: Copy service files
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ directory_systemd }}/{{ item }}"
    owner: root
    group: root
    mode: "0o644"
  loop:
    - seerr-main.service
    - seerr.service
  notify: Restart seerr

- name: Enable and check seerr service
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: seerr
  notify: Restart seerr
